### ISSUE TITLE
About coroutine cancelation

### ISSUE THREAD

**Issue by lparam** [sustrik/libdill#1]
Hi,sustrik.
I think "gocancel" is a very useful API.
Why did you cancel it?

**Comment by sustrik** [comment]
Because it's not yet clear how to do it. This is a complex problem. Not even fathers of UNIX have got it right (see POSIX signal API). In fact, libmill/libdill is part of my long term project to sanely handle asynchronous cancelation.

**Comment by lparam** [comment]
Well, this is a nice project. Thank for your great work.

**Comment by sustrik** [comment]
Fixed. Now there's full-fledged 'gocancel' function.
