### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by paulofaria** [sustrik/libdill#10]
http://libdill.org/documentation.html

The documentation mentions the mailing list, but I can't find a link anywhere. Is there a mailing list yet?
By the way, Libdill is awesome. I was waiting for a release for a long time.

Congratulations!

**Comment by sustrik** [comment]
Thanks!

I've removed the mentions of the mailing list.

I am not sure we need one. The experience with libmill shows that people prefer communicating via GitHub. Anyway, creating it is easy, so if there's popular demand for it, we can create it.

**Comment by paulofaria** [comment]
Awesome! (:
