### ISSUE TITLE
fd_close()

### ISSUE THREAD

**Issue by vlm** [sustrik/libdill#100]
@sustrik, in tcp.c you assert on fd_close(). Why? The close() can legitimately fail, which doesn't constitute an application problem and the app shouldn't fail for not being able to close cleanly.

**Comment by sustrik** [comment]
AFAIK the semantics of errors from close are non-standard and differ among the platforms.

The alternative here would be not to check the error code at all. Which, on the other hand, could lead to leaked file descriptors.

Any ideas of how you would like to handle this?

**Comment by vlm** [comment]
The higher level semantics may well hide the bottom level flexibility. For example, there's no need to support `shutdown(2)` interface on TCP sockets, such API may well still be useful.

Same applies to close: it is OK not to provide any indication of the last state from `close()` to the higher level code.

However, apart from what to return, what to actually do on close errors?

In dsock's case, there are exactly two ways to deal with close errors in case of errno=EINTR:

1. If dsock is used in a preemptively multithreaded environment, it is strictly _unsafe_ to retry the call, fearing close might close some other newly opened descriptor. Therefore, we _must_ accept an fd leak. Hopefully it won't be too frequent.

2. If dsock is being operated in a single threaded environment, it is strictly safe to retry on EINTR in a tight loop; though how many times to loop around EINTR is debatable.

**So to play safe and simple I'd just settle on the first approach for all environments.**

Every other errno on close() error will result in a proper file descriptor closure and won't cause an fd leak.

**Comment by sustrik** [comment]
Generally speaking, +1 for not checking the result.

> Every other errno on close() error will result in a proper file descriptor closure and won't cause an fd leak.

I wouldn't be so sure. POSIX is suspiciously silent on the issue. The only thing it says is that in case of EIO error, the state of the socket is unspecified.

**Comment by vlm** [comment]
Likely won't be a problem in practice: the application domain for dsock is generally socket-oriented code, not filesystem-oriented code.

Meanwhile you could place a reference to this issue in the comments there to maintain context...

**Comment by sustrik** [comment]
Fixed.
