### ISSUE TITLE
[Homepage] Some navigation links are broken

### ISSUE THREAD

**Issue by pudelkoM** [sustrik/libdill#101]
The navigation links (Home, Download, Documentation, Tutorials) on `libdill.org`  are broken on the manual subpages.
E.g.: 
On [Home](http://libdill.org/index.html) ->[Documentation](http://libdill.org/documentation.html): OK
On [brecv](http://libdill.org/man/brecv.html) ->[Documentation](http://libdill.org/man/documentation.html): 404, extra `/man` in the path

**Comment by sustrik** [comment]
Well spotted! Fixed now.
