### ISSUE TITLE
fdin not returning as expected on macOS 10.12.3

### ISSUE THREAD

**Issue by jeremycw** [sustrik/libdill#105]
I the compiled the following with clang version `Apple LLVM version 8.0.0 (clang-800.0.42.1)`
no special options, just `clang test.c -ldill`

```c
#include <stdio.h>
#include <fcntl.h>

#include <libdill.h>

int main() {
  struct ipaddr addr;
  ipaddr_local(&addr, NULL, 5555, 0);
  int ls = tcp_listen(&addr, 10);
  int s = tcp_accept(ls, NULL, -1);
  printf("accpeted: %d\n", s);
  fcntl(s, F_SETFL, O_NONBLOCK);
  fdin(s, -1);
  printf("activity\n");
}
```
When I run the program I can connect to localhost on 5555 and get the accepted printf but I can type away in the telnet session and never get past the `fdin` line. Not sure if I'm doing something wrong or what. Any ideas?

Library is version 1.5 downloaded from libdill.org downloads page.

**Comment by sustrik** [comment]
Reproduced on Linux. Will have a look.

In the meantime: You can't call fcntl of s. It's not a real OS socket.

**Comment by sustrik** [comment]
Ah, you are using fdin() on s which is a libdill handle. fdin() is supposed to be an OS file descriptor.

If you want to read data from s you can do it like this:

```
char c;
brecv(s, &c, 1, -1);
```

**Comment by jeremycw** [comment]
Ah, thanks for looking into this. I thought of that but wasn't sure if reading byte by byte was an intended use case for brecv.

**Comment by sustrik** [comment]
Yes, it's OK. tcp socket reads data from kernel space in batches so reading one byte at a time shouldn't result in massive performance regression.
