### ISSUE TITLE
Compile with TinyCC?

### ISSUE THREAD

**Issue by metadings** [sustrik/libdill#116]
Hello World,

I'd like to use TinyCC to compile `libdill` and `dsock`, I already do so with `nanomsg`.

	./autogen.sh
	./configure --with-gnu-ld CC=tcc
	make

This fails because of

	#if !defined __GNUC__ && !defined __clang__
	#error "Unsupported compiler!"
	#endif

I changed this to

	#if !defined __GNUC__ && !defined __clang__ && !defined __TINYC__
	#error "Unsupported compiler!"
	#endif

However, I didn't succeed because of

	  CC       libdill_la-chan.lo
	  CC       libdill_la-cr.lo
	cr.c:313: error: invalid clobber register 'r8'
	slist.h:40: error: internal compiler error: vstack leak (3)
	make[1]: *** [libdill_la-cr.lo] Error 1

**Comment by sustrik** [comment]
What microarchitecture is that?

**Comment by metadings** [comment]
I'm using x86_64

**Comment by sustrik** [comment]
Then it must be something with the inline assembly used by tinycc. Is there a way to switch to the same assembly the gcc uses?

**Comment by metadings** [comment]
Well no... According to [bellard.org/tcc/tcc-doc.html](http://bellard.org/tcc/tcc-doc.html), TinyCC doesn't support `__attribute__ ((noinline))` and ... well, I don't know, in C :-)

What about MSVC?

**Comment by sustrik** [comment]
No idea. You'd have to define DILL_ARCH_FALLBACK to avoid the assembly parts (MSVC uses Interl syntax, not AT&T syntax) and try.
