### ISSUE TITLE
How to wrap a fd?

### ISSUE THREAD

**Issue by clehner** [sustrik/libdill#117]
Is there a recommended way to turn a file descriptor into a libdill bytestream? The use cases I have in mind are:
- a plugin for the [Dillo](https://www.dillo.org/) web browser: an executable that accepts socket connections on stdin.
- a tool for testing a libdill protocol using stdio: spawn a process and wrap its stdin/stdout with the protocol and pipe it to the parent process's stdin/stdout.

For the first case I think it might work to expose `ipc_makeconn` and use that to wrap stdin. For the second case, I'm not sure.

**Comment by sustrik** [comment]
Have you seen this: http://libdill.org/tutorial-protocol.html ?

While it says 'network protocol' it doesn't necessarily require network to be involved.

**Comment by handicraftsman** [comment]
As i understand, you cannot pass connection handles through threads. This means that you could (in theory) send file descriptors to the libdill-powered threads which will then wrap these fds in tcp/tls connection handles.
