### ISSUE TITLE
hvfs parameters

### ISSUE THREAD

**Issue by paulofaria** [sustrik/libdill#118]
Hello!

I'm trying to implement `hmake` in Swift, but I'm afraid I hit a roadblock. From the tutorials you state:

> The interesting part is that the first argument to the virtual function is no longer the handle but rather pointer to the virtual function table. And given that virtual function table is a member of struct quux it's easy to convert it to the pointer to the quux object itself.

This works pretty well in C, but unfortunately in Swift he don't have such guarantees. We also don't have `offsetof` which makes things even harder. One option would be to add a `void *context` to `hvfs`, `bsock_vfs`, `msock_vfs`, etc. This would make things much easier when wrapping `libdill` in other higher-level languages.

What do you think?

**Comment by sustrik** [comment]
I see your problem.

One way to solve it is the one you propose above.

A different way to do it would be the C++ vfs layout where pointer to the object is passed to a function and first element of the object is supposed to be the virtual function table. I am not sure that would work for Swift though. Can you do any typecasts at all?

**Comment by paulofaria** [comment]
Yeah you can, but I tried the `void *context` approach and it worked great. It's a 4 LOC patch.

**Comment by sustrik** [comment]
Sorry for the delay (I am on a holiday).

Another approach that comes to mind is using hquery. Even now, if you pass specific type ID (e.g. tcp_type) to hquery, it returns raw pointer to the underlying object. Would that solve your problem?

**Comment by paulofaria** [comment]
No problem. Unfortunately the only way I could make it work was with `void *context`. But I decided not to implement `hquery` and handle protocol composition from Swift. Might still be a problem for others, but better wait for new demands, if they surface at all.

Thanks for the attention.
