### ISSUE TITLE
Wait for a coroutine

### ISSUE THREAD

**Issue by jkbbwr** [sustrik/libdill#122]
If I fire a coroutine and I hold the handle how can I wait for it to complete.

**Comment by sustrik** [comment]
You have to create a channel to signal the completion.

**Comment by jkbbwr** [comment]
Does the scheduler not track completion?

**Comment by sustrik** [comment]
It does. However, the info is not accessible to the user.

The idea behind that is that if the parent coroutine waits for the child coroutine it probably wants some kind of result from it (at least success/failure code). And given that we the library has no idea about the type of the result (int, string, a structure?) it leaves it to the user to create a channel of appropriate type to indicate completion.

**Comment by jkbbwr** [comment]
The main usecase I was going after was to not exit main until all coroutines resolved somehow. Don't care about results. But I see your point
