### ISSUE TITLE
can't run more than 32.7k concurrent coroutines

### ISSUE THREAD

**Issue by fatihky** [sustrik/libdill#130]
Hi,
I am trying to start many coroutines that only calls `msleep` and exits. My example stops working after completing 32.700th `msleep`. Here is my example code:

```c
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h>
#include <stdlib.h>
#include <unistd.h>
#include <libdill.h>

int completed = 0;
long count;

static coroutine void worker(int ch) {
    int val = 1;
    msleep(now() + 1000);
    completed++;
    if (completed % 100 == 0) {
        printf ("completed: %d\n", completed);
    }
    if (completed == count) {
        printf("all coroutines completed\n");
    }
    int ret = chsend(ch, &val, sizeof(val), -1);
    if (ret != 0) {
        printf("ret %d\n", ret);
    }
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("usage: go <coroutines>\n");
        return 1;
    }
    count = atol(argv[1]);

    int ch = chmake(sizeof (int));
    for (long i = 0; i != count; ++i) {
        int h = go(worker(ch));
    }

    printf("started %ld coroutines\n", count);

    int val;
    for (long i = 0; i != count; ++i) {
        int ret = chrecv(ch, &val, sizeof (val), -1);
        if (ret != 0) {
            printf("ret %d\n", ret);
        }
        if (i % 100 == 0) {
            printf ("i: %ld\n", i);
        }
    }

    return 0;
}
```

And here is sample output:
```
...
completed: 32300
completed: 32400
completed: 32500
completed: 32600
completed: 32700
i: 32300
i: 32400
i: 32500
i: 32600
i: 32700
```

**Comment by sustrik** [comment]
That' suspiciously close to 32768. I'll have a look.

**Comment by sustrik** [comment]
Reproduced.

**Comment by sustrik** [comment]
You are not checking the errors from  go() function. It returns ENOMEM error.

**Comment by fatihky** [comment]
thank you for the response

**Comment by fatihky** [comment]
Currently my program is using 258MB of memory for the 32.7k coroutines. After that count, it stops starting new coroutines.

I couldn't get why I am getting ENOMEM after that count. If memory usage increases linearly, my program should use ~800MB of ram for the 100k coroutines. My server has free ram as that much, so it could allocate 800MB of memory.

Do you have any idea what causes this?

**Comment by sustrik** [comment]
There's also stack allocated for each coroutine. At least 1 page of bottom of the stack and 1 guard page at the top of the stack.
