### ISSUE TITLE
test suite fails for test ippadr on Fedora 26

### ISSUE THREAD

**Issue by D4N** [sustrik/libdill#135]
I wanted to give libdill a try (it looks really promising and the API is very pretty) and tried to build it on Fedora 26. Building works without a problem but the test suite fails at the test `ippadr`. The test-suite.log indicates the following error:
```
FAIL: tests/ipaddr
==================

lt-ipaddr: tests/ipaddr.c:75: main: Assertion `rc == 0' failed.
FAIL tests/ipaddr (exit status: 134)
```

I have taken a look at the test and if I understand it correctly, it tries to perform a dns resolution off `large-dns-response-[1,2,4,8]k.lionet.info`? I have run this in two different networks (at home and at work) but in both cases the test fails. Running it with strace yields the following output around the failure:
```
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
bind(4, {sa_family=AF_INET, sin_port=htons(10218), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.254")}, 16) = 0
sendto(4, "\317/\1\0\0\1\0\0\0\0\0\0\25large-dns-response-"..., 51, 0, NULL, 0) = 51
recvfrom(4, 0x155cd94, 768, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN, {u32=4, u64=4}}) = 0
epoll_wait(3, [], 128, 4998)            = 0
epoll_ctl(3, EPOLL_CTL_DEL, 4, 0x7ffc0cfc59e4) = 0
close(4)                                = 0
```

I was however able to resolve the `large-dns-response-[1,2]k.lionet.info` hosts with `dig` using Google's DNS server (8.8.8.8) but not the other two (dig only outputs `;; Truncated, retrying in TCP mode.` and then times out with `;; Connection to 8.8.8.8#53(8.8.8.8) for large-dns-response-4k.lionet.info failed: timed out.`).

Would it be possible to modify this test so that it would succeed without requiring to modify the current DNS setting (e.g. in the case when it is not possible, like on a CI server that I do not administer)?

Thanks in advance and also for your work on this library!

**Comment by sustrik** [comment]
I guess we should just remove the test, given that it's not hermetic (i.e. depends on an external resource).

**Comment by D4N** [comment]
I don't know if that's possible, but one could try to mock the reply from the DNS and do all the post processing by libdill. Thereby one could still test the routine, yet would not rely on an external DNS. But I know this can be very tricky to do in C.

**Comment by sustrik** [comment]
Not worth it IMO. DNS support in libdill is a thin wrapper over a 3rd party dns.c library so we would end up testing 3rd party code anyway.

**Comment by D4N** [comment]
> Not worth it IMO. DNS support in libdill is a thin wrapper over a 3rd party dns.c library so we would end up testing 3rd party code anyway.

Makes sense. Feel free to close this issue at your convenience then.

**Comment by sustrik** [comment]
Done.
