### ISSUE TITLE
[Question] Could libdill be used in a bare-metall environment?

### ISSUE THREAD

**Issue by D4N** [sustrik/libdill#139]
I am developing a lot of software on an ARM Cortex M4 (a simple 32 bit MCU without an MMU and without an operating system) and have been searching for ways how to enable some lightweight concurrency. libdill looks very promising as it can do most of the things that I want (simple single threaded structured concurrency & channels).

However libdill uses Unix system calls internally which are of course not available in a bare metal environment. Since I am not too familiar with the internals, how hard would it be to create a stripped-down version of libdill that could run without an operating system and would support basic concurrency but not the networking part?

If that would be possible, would you want to merge such a feature into libdill?

**Comment by sustrik** [comment]
You can disable the sockets part of the library by specifying --disable-sockets in ./configure. When done, I think there are only few system calls, namely select (or equivalent) and gettimeofday (or equivalent). We would have to discuss how to emulate them.

**Comment by D4N** [comment]
I think implementing sleep should be left to the "user" (the programmer using libdill), since there is no standard way how to implement that in bare metal environments. For example Cortex M processors usually support a SysTick interrupt, which can be used for coarse measurements. But how the SysTick actually behaves (which clock drives it, when the interrupt fires, what the clock frequency is, etc) is not standardized, so anyone using libdill should probably supply it with a custom `sleep()` function. The current time is basically the same story (the MCU might or might not have a RTC which might or might not be precise enough).

Poll on the other hand would be a very nifty thing to have. While there are not standard file descriptors in embedded devices, one has to usually wait until some periphery has data available (like an uart, spi, a sensor, ...) which can trigger an interrupt (or be found by polling a register). Providing a uniform interface for this would be **extremely** convenient to have. Having the option to turn custom interrupts/events into events which can be awaited by `poll()` or `select()` would be basically what I need in most cases but I don't know if that's possible in the scope of libdill.

**Comment by sustrik** [comment]
Ok, in that case I think it's just a metter of compiling with --disable-sockets and implementing your own poll function. The API you need to implement is in pollset.h. The library already have several implementations (poll, kqueue, epoll) so you can look at those as an example.

**Comment by D4N** [comment]
Unfortunately, I haven't been able to follow up on this due to time constraints. Since the project for which I wanted this is history now and the question has been answered, I'll close this so that it doesn't stay around for ever.

Thanks again for your answers and your work on libdill & libmill @sustrik!

**Comment by sustrik** [comment]
You are welcome!

**Comment by raveslave** [comment]
Sorry for posting in a closed issue. I'm also interested in this, curious if there has been any more work put into this?
