### ISSUE TITLE
Handle Example

### ISSUE THREAD

**Issue by paulofaria** [sustrik/libdill#14]
Could you give me an example of an use case in which one would need to create his own handler type, please?

Reference:
http://libdill.org/handle.html

**Comment by sustrik** [comment]
They are a scaffolding for future work on sockets. In short, exactly the same use case of file descriptors.

**Comment by paulofaria** [comment]
Hmm.. so a in libdill a socket would be represented by a handle instead of libmill's `tcpsock`?

**Comment by sustrik** [comment]
Yes. I've already done some experimenting with the API, have a look, for example, here: https://github.com/sustrik/dillsocks/blob/master/sock.c#L71

**Comment by paulofaria** [comment]
Nice! I'll take a closer look at `dillsocks` later. Seems very interesting.
