### ISSUE TITLE
Windows/MSVC support

### ISSUE THREAD

**Issue by sustrik** [sustrik/libdill#141]
This is partially done on branch https://github.com/sustrik/libdill/tree/windows.

However, I don't own a Windows machine. Help wanted.

**Comment by sustrik** [comment]
MSVC doesn't support statement expressions. That may be a problem.

**Comment by redxu** [comment]
Oh, I suggest you can first implement mingw-gcc on windows. MSVC do not have standard c implement.
MSVC users can use mingw-gcc dll also.

**Comment by sustrik** [comment]
Fair enough. This is not going to work. Closing the ticket.
