### ISSUE TITLE
Detached coroutines

### ISSUE THREAD

**Issue by sustrik** [sustrik/libdill#142]
Use case: I am listening for new TCP connections, I launch a new coroutine for each of them. However, I don't want to keep a list of them and do the terminal handshaking with them so that I can deallocate the stacks. I want stacks to deallocate themselves after the coroutine finishes. That being said, I still want a way to terminate the running coroutines if I am about to exit current scope.

API proposal:

// Creates a container to manage a set of cotoutine handles.
int hset(void);
// Launches a coroutine to be managed by hset.
int go_set(int set, fx());

When a coroutine within the set finishes, its stack is automatically deallocated.

When the set is closed, all coroutines in the stack are hclosed.

When hdone() is called on the set, hdone() is called on all coroutines within the set (i.e. their control channels are hdone'd).

**Comment by handicraftsman** [comment]
You could add go_detached function which basically starts a coroutine and a destructor which frees all allocated memory after coroutine finishes.

**Comment by sustrik** [comment]
I've decided not to implement this functionality as it breaks the "structured concurrency model".
