### ISSUE TITLE
Coroutine Local Storage Example

### ISSUE THREAD

**Issue by paulofaria** [sustrik/libdill#15]
Could you give me an example of an use case in which one would need to use the coroutine local storage, please?

Reference:
http://libdill.org/cls.html

**Comment by sustrik** [comment]
Hopefully, you won't need it at all. But, generally speaking, the same scanarios as for TLS.

For example, libdill is using coroutine-local flag internally to remember whether it's in scope of a hlcose() function and whether is should thus fail blocking calls with ECANCELED error.

**Comment by paulofaria** [comment]
Nice, thanks!
