### ISSUE TITLE
[Question] threadpool with libdill?

### ISSUE THREAD

**Issue by 50hz** [sustrik/libdill#155]
I am trying to move some of my libuv-based application to use libdill instead. libuv has built-in thread-pool but apparently, this is not the case for libdill? which thread-pool library would you recommend that will work well with libdrill? thanks

**Comment by 50hz** [comment]
what I'm really asking is: what is the best way to make libdill multi-core friendly?

**Comment by 50hz** [comment]
it is indeed a (tcp-based) server but the limitation is I can only have 1 port exposed, I can potentially run a load-balancer in front of those single-threaded servers but it sounds a bit overkill? I thought it might be better to have 1 process running (bound to 1 port) with a thread pool of num of CPUs size that do the actual work?

**Comment by handicraftsman** [comment]
That is possible. You could create a thread pool and then distribute file descriptors using tcp_fromfd, but this function is not in release yet. I think there will be more updates to it in future.

**Comment by 50hz** [comment]
@handicraftsman thanks for the idea, do you have a thread-pool library to recommend that will work well with libdill? thanks

**Comment by handicraftsman** [comment]
No.

**Comment by 50hz** [comment]
thanks, what is the current status of tcp_fromfd? is it ready but just sitting in master (but not release) or it is still in dev?

**Comment by sustrik** [comment]
I've just released a new version (2.9) that contains it.

**Comment by 50hz** [comment]
seeing it now, thank you very much!

**Comment by 50hz** [comment]
@handicraftsman just wanted to make sure I understand your suggestion correctly (after reading the document @sustrik just released). 

Did you mean I should create N (number of threads) socket_fd and wrap them with tcp_fromfd, then pass the socket (s_1, s_2 ... s_N) to each thread, so that the main thread (who receives requests via TCP port) can distribute requests to those threads via e.g. msend(s_x)?

**Comment by handicraftsman** [comment]
Ugh, you cannot transfer libdill handles. You should use fromfd in destination threads instead.

**Comment by 50hz** [comment]
got you, thanks
