### ISSUE TITLE
Do channels work across procs?

### ISSUE THREAD

**Issue by paulofaria** [sustrik/libdill#16]
If I send a channel from the main coroutine to a proc, could I retrieve values sent to the channel in the proc from the main coroutine?

**Comment by sustrik** [comment]
No they don't.

**Comment by paulofaria** [comment]
What would be the best way to communicate across procs? Would it be possible to have channels work across procs?

**Comment by sustrik** [comment]
UNIX domain sockets.

That being said, I think it's wise to treat different processes as if they were running on different machines (communicating via TCP and so on). That way the application can scale to use all cores on the machine and beyond that point it can scale further to multiple machines, no code change needed.

I wonder whether encourage forking by providing an easy way to fork processes (proc) is a good idea at all...
