### ISSUE TITLE
dill_prologue checks for dill_allocstack failure incorrectly

### ISSUE THREAD

**Issue by michaelforney** [sustrik/libdill#17]
I built and ran `./perf/go 1` and it segfaulted.

It looks like this is because `dill_prologue` subtracts from the result of `dill_allocstack`, and *then* checks for `NULL`, when it should be the other way around.

As for why I ran out of memory, I think it is because perf/go.c is not closing the handles returned from `go(worker())`, so none of the stacks get reused.

**Comment by sustrik** [comment]
Fixed. Can you check now?

**Comment by michaelforney** [comment]
Yep, thanks!
