### ISSUE TITLE
Is it possible to only retrieve the value after it is done ? Something like a future/promise

### ISSUE THREAD

**Issue by GuacheSuede** [sustrik/libdill#176]

**Comment by sustrik** [comment]
You need to create a channel for that. Send the result to the channel once you are done. Let client do blocking recv on the channel. It's basically the same as in Golang.

**Comment by GuacheSuede** [comment]
@sustrik I see, Thanks. Does libdill fully use all the cores available on the machine that it is running on ?

**Comment by sustrik** [comment]
It's thread-agnostic. If you create as much threads as there are processor cores, you can use them all. However, keep in mind: 

"You can use libdill in multi-threaded programs. However, individual threads are strictly separated. You may think of each thread as a separate process.

In particular, a coroutine created in a thread will be executed in that same thread, and it will never migrate to a different one.

In a similar manner, a handle, such as a channel or a coroutine handle, created in one thread cannot be used in a different thread."

**Comment by sustrik** [comment]
Coroutines are always isolated in a single thread. They are never migrated between threads. Each thread has its own scheduler, so there's no performance impact.

libuv does more or less the same thing as libdill, why would you want to use both?

**Comment by GuacheSuede** [comment]
> libuv does more or less the same thing as libdill, why would you want to use both?

Comparing between libdill and libuv to be used, performance wise they should be abt the same right ?

**Comment by GuacheSuede** [comment]
@sustrik May I ask, is it correct understanding libdill executes on a single kernel thread only ?

**Comment by sustrik** [comment]
As stated above: You can have as many threads as you pthread_create, but they are mutually isolated. I.e. a coroutine running in one thread won't be ever migrated to a different thread.
