### ISSUE TITLE
Please pre-generate the `./configure` for the source tarball releases

### ISSUE THREAD

**Issue by mentalisttraceur** [sustrik/libdill#179]
Please pre-generate the `configure` script, because that is the intended best practice with Autotools.

Autotools was intended to be used that way because the `configure` script by itself embodies everything needed to build on any supported system, and running `./configure` itself doesn't depend on having any of the Autotools installed, significantly simplifying the build process and dependencies for people who build and package software from source.

P.S. Since the configure is a generated artifact always and is always the same form the same source no matter what system it's built on, the `configure` only needs to be included in the source tarball *releases*, and does not actually need to be checked into version control.

**Comment by sustrik** [comment]
It's already in the tarball, no?

**Comment by mentalisttraceur** [comment]
@sustrik Ah, I see: It *is* in the tarball on your website, but did not seem to be in the tarball I downloaded from the release page here on GitHub.

I was initially trying to grab it from GitHub because I try to use TLS for my downloads of software I build from source whenever possible.

Is intentional for the release tarballs on GitHub to be different from the release tarballs on your site? Or too inconvenient to change?

**Comment by sustrik** [comment]
GitHub creates "releases" automatically each time you create a git tag. But they are not real releases, they are just tarballs of whatever exists in the repo at the time. I don't think you can switch this functionality off. Ideas of how to get rid of them are welcome.

**Comment by mentalisttraceur** [comment]
Understood. Thank you for clarifying.
