### ISSUE TITLE
Relationship to libmill

### ISSUE THREAD

**Issue by theduke** [sustrik/libdill#19]
Since I don't really know where else to ask, I'll just do it here:

How do you see this library in relation to libmill?
I know the FAQ has a section about it, but do you consider libdill a replacement that should be preferred over libmill?

What are your future plans? To prefer and focus development on libdill? 
Develop both actively?

**Comment by theduke** [comment]
Also, since a lot of people who know about libmill might stumble upon this, I would consider putting an explanation right on the home page.
I was definitely confused at first and had to dig into the FAQ.

**Comment by sustrik** [comment]
libmill is done. If you find any bugs, I'll fix them but that's it. libdill is in beta, i.e. it can still change a bit.

**Comment by sustrik** [comment]
I've also improved the libmill vs. libdill text on the website.

**Comment by theduke** [comment]
Thanks for clearing it up a bit.

**Comment by laoshaw** [comment]
both libmill.org and libdill.org are gone
