### ISSUE TITLE
Are there the flush operation for sockets?

### ISSUE THREAD

**Issue by Gymmasssorla** [sustrik/libdill#193]
Has LibDill the flush operation for stream-based sockets? In other words, how can I send all remaining data in a sending buffer to a remote endpoint?

**Comment by sustrik** [comment]
You don't have to. It's done automatically.

**Comment by Gymmasssorla** [comment]
So LibDill hasn't got a sending buffer, all the data is written to a destination at the moment it was accepted by `bsend()`, `bsendl()` functions?

**Comment by sustrik** [comment]
Yes. That's the case.

It would be nice to add that, but I would like to avoid exlicit flush. AFAICS it can be done by automatically flushing when the tx buffer is full AND when scheduler has no other work to schedule.

**Comment by Gymmasssorla** [comment]
Thank you
