### ISSUE TITLE
Warnings when compiling with clang

### ISSUE THREAD

**Issue by manvscode** [sustrik/libdill#20]
The following warnings appear when compiling with clang:

<pre>
In file included from pollset.c:38:
./kqueue.inc:95:9: warning: implicit declaration of function 'close' is invalid in C99 [-Wimplicit-function-declaration]
        close(dill_kfd);
        ^
./kqueue.inc:173:14: warning: initializing 'int *' with an expression of type 'uint32_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
        int *pidx = &dill_changelist;
             ^      ~~~~~~~~~~~~~~~~
./kqueue.inc:177:18: warning: assigning to 'int *' from 'uint32_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
            pidx = &dill_fdinfos[*pidx - 1].next;
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./kqueue.inc:202:39: warning: | has lower precedence than ==; == will be evaluated first [-Wparentheses]
        if(!dill_list_empty(&fdi->in) | fdi == dill_parentinfo) {
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
./kqueue.inc:202:39: note: place parentheses around the '==' expression to silence this warning
        if(!dill_list_empty(&fdi->in) | fdi == dill_parentinfo) {
                                      ^
                                        (                     )
./kqueue.inc:202:39: note: place parentheses around the | expression to evaluate it first
        if(!dill_list_empty(&fdi->in) | fdi == dill_parentinfo) {
                                      ^
           (                               )
</pre>

$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by sustrik** [comment]
Thanks for spotting it! It's fixed now.
