### ISSUE TITLE
[Feature] Generating man pages

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libdill#28]
The documentation for libdill is quite comprehensive on the website and structured in a manpage sort of format.  [ronn](http://rtomayko.github.io/ronn/ronn-format.7.html) can generate manpages from Markdown - perhaps some investigation should be made to see if it is possible to integrate optional manpage building support if ronn is installed.  This would be for offline manpage use on the application developer's system.

``` shell
$ ./configure --enable-docs # checks if ronn is installed
$ make docs # build documentation only
$ make # only build documentation if ronn is enabled in configure
```

As the documentation is in a separate branch, perhaps having documentation distributed separately is a viable alternative as well instead of complicating libdill's build system.

**Comment by raedwulf** [comment]
A third idea would be to build the documentation using travis to either create this separate package or include it within libdill (if travis deployment is currently set up).

**Comment by sustrik** [comment]
The fun with generating man pages IIRC is that they have to be generated in "make dist" step, i.e. before build, to be packeged in the tarball. However, given that not everybody has the appropriate toolchain installed, man page generation should happen only on demand. Yet, customisation with autotools is done in configure step which comes after make dist :/

We've had a hack of some kind in nanomsg, but it wasn't nice.

On the other hand, generating man pages into a separate package should be easy.

The question is whether people managing packages for distros are OK with the two-package approach.

**Comment by raedwulf** [comment]
I cannot say for all distributions but from what I've seen people make do with what upstream provides.  

Having a separate package just involves another package to be downloaded - this is normally quite easy to add into a package build script.  Debian-based distributions often have packages with separate documentation (even if the original distribution didn't) so probably a separate package would in fact be more flexible for a package maintainer.

**Comment by sustrik** [comment]
Ok, let's try to do the separate package then.

**Comment by vlm** [comment]
[asn1c](https://github.com/vlm/asn1c/blob/master/configure.ac#L124) uses PANDOC to generate man pages (and places it in the repo, for easy access via `man ./filename.1`). The regeneration only happens on systems with pandoc.

**Comment by sustrik** [comment]
That means that generating documentation and checking it in into git is a manual step in the release prodcedure, similar to bumping the version. Right?

**Comment by vlm** [comment]
I consider it part of the documentation _creation_ stage. When you're done with source, you gen the `.1` to check that it rendered correctly. This is where you check the result right in, right then. No need to delay.

Documentation is something that people want to have more control over, including controlling the aesthetics of the result. This for me excuses the need to keep the generated file in the repo: the generated file is the one you put there, after your version of the tool generated it and you checked the delta yourself, to avoid some embarrassing typos and formatting errors.

**Comment by raedwulf** [comment]
I should be done with this today: I've updated `configure.ac` and `Makefile.am` to check if `git` and `pandoc` are available and then downloads and builds the documentation from the `gh-pages` branch.

**Comment by raedwulf** [comment]
For reference,  pull request #53

**Comment by raedwulf** [comment]
Closing because of merge.
