### ISSUE TITLE
example crash 

### ISSUE THREAD

**Issue by lparam** [sustrik/libdill#3]
1. make check
2. valgrind \
    --gen-suppressions=no \
    --tool=memcheck --leak-check=full --show-leak-kinds=all \
    --free-fill=0x0 \
    tests/.libs/example

==21902== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==21902==  Access not within mapped region at address 0x100000007
[1]    21902 segmentation fault (core dumped)  valgrind --gen-suppressions=no --tool=memcheck --leak-check=full

**Comment by sustrik** [comment]
Given that the problem doesn't happen outside of valgrind, I wonder whether valgrind is having hard time dealing with libdill's fractured stack.

**Comment by reqshark** [comment]
related discussion https://github.com/sustrik/libmill/issues/132

**Comment by sustrik** [comment]
This problem should be fixed now. Please check.

**Comment by sustrik** [comment]
No response. Closing the issue.
