### ISSUE TITLE
[Experiment] Coroutine Closures

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libdill#31]
Implemented coroutine closures using GCC's nested-functions and Clang's -fblocks.

https://github.com/raedwulf/libdill/commit/351e8ff65df4e72260b6ded051ae4c2b348d9b5d

Pros:
1. Works brilliantly with GCC.
2. It is possible to force the closure call not to be inlined at the call-site!
3. Performance is comparable, if you now force inlining on the previously non-inlined methods.
4. The compiler is a lot more predictable with closures and you can now declare the coroutine contents within `go()` without breaking your code horribly:

``` C
int cr1 = go(
         int i;
         for(i = 0; i != 3; ++i) {
             sum += 7;
             int rc = yield();
             assert(rc == 0);
         }
     );
```

Cons:
1. Totally non-standard, but then statement expressions are not standard either.
2. Clang needs compiler flag -fblocks and needs https://github.com/mackyle/blocksruntime if building on non-OSX.
3. Clang does not support accessing arrays within the closure.
4. Performance of coroutine creation and context switching ~~roughly halves~~ loses 20-30% when inlining of the functions in closures isn't performed on both GCC and Clang when compared with the non-closure method.

**Comment by raedwulf** [comment]
Both can be technically supported at the same time, but then it does complicate the API:
```C
coroutine void worker(int count, int n) {
    int i;
    for(i = 0; i != count; ++i) {
        sum += n;
        int rc = yield();
        assert(rc == 0);
    }
}
// ...
int cr1 = gofast(worker(3,7)); /* only works with single function calls declared using coroutine */
int cr2 = goclosure( /* works with everything you want to throw at it (except for Con 3 above) */
         int i;
         for(i = 0; i != 3; ++i) {
             sum += 7;
             int rc = yield();
             assert(rc == 0);
         }
     );
```

**Comment by paulofaria** [comment]
@raedwulf not being able to access arrays inside a block is very odd. I don't remember ever having that problem. did you find any information about this on the web?

**Comment by raedwulf** [comment]
Sorry for the repeat reply,  @paulofaria For completeness, it might be because clang copies the locally captured variables and i suspect they wanted to prevent accidental copying of large arrays...

**Comment by sustrik** [comment]
This looks like going in the right direction!

What I really like is how it makes current behaviour (go(fn());) just a special case of generic pattern (go(block);).

That being said we have to make sure that we won't hurt portability, i.e. prevent the case where code written for gcc doesn't work with clang or code written for linux doesn't work for osx.

To do that we should be explicit about what's in scope. I think:

1. gcc & clang - That covers most of the use cases. Both compilers are free, clang is even permissively licensed so it's not like we are not putting some big barriers to entry here.
2. all POSIX-compliant systems (Win & VMS are out of scope) - it may also be acceptable to ignore some old non-fully-POSIX-compliant UNIXes 
3. all microarchitectures - there should always be a fallback code for non-x86 archs; at the moment we don't support upward-growing stacks, but at least we should keep the architecture flexible enough to implement that if need be

**Comment by sustrik** [comment]
Btw, do you know why the performance loss? Once would expect inlined code run faster than non-inlined one?

**Comment by sustrik** [comment]
Some thoughs after looking into details:

1. I love the increased stability, i.e. no UB when coroutine specifier is omitted.
2. Would it make sense to drop clang support until it get full feature parity with gcc?

**Comment by sustrik** [comment]
I love the increased stability, i.e. no UB when coroutine specifier is omitted. However, it introduces instability of its own. From gcc docs: "If you try to call the nested function through its address after the containing function exits, all hell breaks loose."

Imagine the closure uses a variable from the containing scope. The coroutine runs for a while, then parent coroutine exits (or just unwinds the stack a bit). The child coroutine is now referencing stuff on the deallocated stack. 

So, I guess, we are left with the existing constraint: go() can contain only a single function all. Good news: We don't need coroutine specifier. Bad news: With clang you need an add-on and a compiler option.

**Comment by sustrik** [comment]
Btw, a pathologic caseL

```
go(foo(msleep(now() + 1000)));
```

Note how context switch occurs before coroutine is even called. Do we want to support this kind of thing?

**Comment by sustrik** [comment]
I've made a lot of comments here, then deleted them so that I can focus on the core issue.

This works:
```
int a = 3;
go(
    foo(a);
);
```

This does not:
```
int a = 3;
go(
    yield();
    foo(a);
);
```
The parent coroutine could have exited during the yield() call. Thus, 'a'  in 'foo(a)' is referencing freed memory.

Pathological case:
```
go(
    foo(yield(), a);
);
```
Yield is called as first argument is evaluated. Parent coroutine exits (or unwinds stack a bit) and evaluation of the second parameter fails.

As can be seen, this is a problem both with current implementation and the proposed one. However, the code blocks inside go() make the problem obvious.

**Comment by raedwulf** [comment]
That's a tough problem... I think this explains why clang copies all the captured variables from the containing stack in its block implementation - it is to prevent this issue!(https://github.com/mackyle/blocksruntime is actually MIT-licensed and pretty small so could be embedded so people wouldn't need to hunt for dependencies).

Sounds like we need to emulate that in coroutines:
```C
goclosure(
    copy_capture(a, b, c);
    yield();
    foo(a);
, a, b, c);
```
Unfortunately, as I think about the details, I'm not sure if we can make it cleaner for GCC.  The parameterised a first lets the macro copy `a` and assigns it to a new generated symbol.  We need some way to referenced the copied variable.  The new macro `copy_capture` does just this.
Note, serious macro magic is required to achieve this, but it is possible. `goclosure` generates a unique reference to a capture variable starting from a some index counter and another index to indicate position in capture variable list.  This index counter is recorded and pasted with `copy_capture` so you'll have something like `copy_capture5` and that gives a unique identifier for each parameter.
This, like clang's blocks, does not work for arrays references.

For the current implementation, it is easier, but still clunky,
`yield` passed as a parameter in the current implementation need to be passed as a symbol which is then processed after the parameters are passed.  For example, a `lazy_yield`, which is checked by the 
coroutine function and processed once the body executes.

```C
/* Current implementation fix */
go(foo(lazy_yield, a)); /* foo check for lazy_yield and then executes it at the start of the function */
```

Performance drops with closures as I suspect there's a lot of stack frame copying going on and this happens with each coroutine call.

**Comment by raedwulf** [comment]
Is there a use-case for `go(foo(yield(), a));` ? The single function call variant.

**Comment by sustrik** [comment]
A problematic use case is this one:

```
int a = 3;
go(foo(bar(), a));
```

Is it correct or not? Depends on whether bar() or any function it calls -- at whatever nested level -- performs a context switch. That's a non-local property, so the users should not do it.

What about saying in docs that all arguments to coroutine should never be function calls?

**Comment by raedwulf** [comment]
Yeah recording it in docs for the current implementation would be good and recommend calling in the body.  If closures can be figured out then we could allow it for that.

**Comment by sustrik** [comment]
On unrelated topic: Do you know what causes the slowdown when using gcc nested functions? (cons. no 4.)

**Comment by raedwulf** [comment]
I looked briefly at the generated listing and it seems there's just simply a lot more pushes/pops generated by default and the compiler didn't know how to get rid of them.  If you force more inlining using inline keyword it regains most the speed and with -O3. I'll investigate a bit later.

**Comment by sustrik** [comment]
I was thinking about this some. As for now it seems that the "block of code inside go statement" approach, however nice it looks, has a systemic problem: It's never clear whether variables from the surrounding scope can be used at any particular moment.

A "function-containing go statement" has the same problem but it can be avoided by requiring function arguments not to be function calls themselves. (Note that there's no such easy measure for block-based approach.)

Looking at how the situation would change if there was direct support form the compiler (or some black magic to emulate it), what's required is evaluating any values needed by the coroutine first, then doing the stack trickery and copying the values to the new stack. For function-based go() this means copying the arguments of the function. In the block-based go() it means copying the entire stack frame of the caller. The former is definitely more in line with C language philosophy.

In the end I would say it's better to drop the idea of block-based go() altogether.

**Comment by raedwulf** [comment]
That's fair enough, it was originally an attempt to stabilise the code generation output of the standard `go(worker(a,b,c));`
