### ISSUE TITLE
Compatibility documentation

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libdill#35]
A page for the documentation:

https://gist.github.com/82a7cb6d3c6ecff92541b2501d070fe6

Aspects of it are relevant to #36 and ~~#37~~

**Comment by raedwulf** [comment]
Updated this documentation.

**Comment by sustrik** [comment]
Copied here: http://libdill.org/compatibility.html

I've simplified the text a bit to make it more understandable for people not familiar with the details of the project.
