### ISSUE TITLE
Add dill_fdwait for bi-directional event monitoring

### ISSUE THREAD

**Issue by robertjpayne** [sustrik/libdill#40]
Libdill has no API to wait on a file descriptor for either `FDW_IN` or `FDW_OUT` and return the the events that apply.

An argument has been made that each event should be managed in it's own co-routine but I believe this increases the complexity of implementing bi-directional protocols that are not FIFO such as WebSockets / HTTP/2 and hampers integration with existing protocol libraries.

Take for example an implementation of `nghttp2` on libmill:

```
    while (nghttp2_session_want_read(connection.session) ||
           nghttp2_session_want_write(connection.session)) {
        int events = mill_fdwait_(fd, FDW_IN | FDW_OUT, -1, NULL);
        
        if ((events & FDW_IN) && nghttp2_session_want_read(connection.session)) {
            if (nghttp2_session_recv(connection.session) < 0) {
                die("Connection error");
            }
        }
        
        if ((events & FDW_OUT) && nghttp2_session_want_write(connection.session)) {
            if (nghttp2_session_send(connection.session) < 0) {
                die("Connection error");
            }
        }
        
        if (events & FDW_ERR) {
            die("Connection error");
        }
    }
```

Is there an easy way to accomplish something similar in libdill?

**Comment by sustrik** [comment]
What's nghttp2_session_want_read/write() ?

**Comment by raedwulf** [comment]
My memory of nghttp2 is a bit rusty, but if I remember nghttp2 keeps an internal state of the HTTP/2 protocol and when it needs more data, it will set either `nghttp2_session_want_read(s)` or `nghttp2_session_want_write(s)` to be passed to user code to wait on sockets etc.

@robertjpayne I think the best way is to have two long-running coroutines which keep waiting or have quick coroutines firing constantly:

```C
coroutine void reader() {
        while (nghttp2_session_want_read(connection.session)) {
        int rc = fdin(fd, -1);
        if (nghttp2_session_recv(connection.session) < 0) {
                die("Connection error");
        }
    }
}
```

If you could test the performance of short-lived coroutines, that would be amazing!

**Comment by raedwulf** [comment]
@robertjpayne Can we close this if you're happy?

**Comment by robertjpayne** [comment]
Yup actually I'm happy :)
