### ISSUE TITLE
Compilation error on MacOSX 10.11, libdill0.9-beta

### ISSUE THREAD

**Issue by eax** [sustrik/libdill#42]
I've been using libdill-0.5 for sometime with no problem, then I tried to switch libdill-0.9-beta to give it a try. However, my project started complaining about `Conflicting types for 'hcreate'`. These are the conflicting types. I'm using XCode to compile my project on MacOSX 10.11 w/ clang

`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
`

Previous declaration (as shown by Xcode) in `/usr/include/search.h`:
`__BEGIN_DECLS
int	 hcreate(size_t);
`

Conflicting declaration from `libdill.h`:
`
DILL_EXPORT int hcreate(struct hvfs *vfs);
`

Any ideas?

**Comment by sustrik** [comment]
A naming conflict. Can you have a look at /use/include/search.h? What project does it belong to?

**Comment by eax** [comment]
It belongs to BSD library. No specific project I guess:

 ```
Written by J.T. Conklin <jtc@netbsd.org>
 Public domain.
 
 $NetBSD: search.h,v 1.12 1999/02/22 10:34:28 christos Exp $
 $FreeBSD: src/include/search.h,v 1.10 2002/10/16 14:29:23 robert Exp $
```

**Comment by sustrik** [comment]
Oh, it's posix: http://pubs.opengroup.org/onlinepubs/7908799/xsh/hcreate.html

We have to rename that function.

**Comment by eax** [comment]
Oops :) I can do that if you will.

**Comment by sustrik** [comment]
Done in head.

hcreate() -> hmake().
