### ISSUE TITLE
Undocumented special meaning of passing 0 to deadline

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libdill#55]
I noticed in `chan.c` you assume that 0 in deadline returns immediately.
This is incorrect because the parameter is `deadline` and 0 should be treated as a wrap-around time-value especially since we use `CLOCK_MONOTONIC` on linux which could use any arbitrary starting point.

In practice, bugs resulting from this are unlikely.  We should, however, either remove this behaviour and tell the user to use `now()`, or document this behaviour and change the implementation `now()` to start at timestamp 0 (record application start time at initialisation and subtract).

`now()` should be documented that it does not return a time value that is valid across instances of libdill cross-process.  Although it can still be used it within multiple contexts of the same process.
Maybe a compromise is to provide a easy-to-use unix-time conversion function (at millisecond range).

**Comment by raedwulf** [comment]
A third option, `time_t` is specified to be signed -- therefore any negative value would be a viable special value instead of 0.

**Comment by raedwulf** [comment]
Mmm thinking about this further, we do not deal with integer overflows (being pedantic that the source of bugs would stem from CLOCK_MONOTONIC having an arbitrary start point).

Starting from 0 will be sufficient (64-bit times will fall into don't care regions), or implementing a wrap-around add function.  I think starting the clock from 0 would be better.

**Comment by sustrik** [comment]
Can we simply make sure that now() is never 0 by adding 1 to the result?

**Comment by raedwulf** [comment]
It could still fail if `CLOCK_MONOTONIC` makes `clock_gettime` return an abnormally high time value that could wrap.

**Comment by raedwulf** [comment]
#57 I believe should have better behaviour... I just need to check if I did an off-by-one error.

**Comment by raedwulf** [comment]
Okay fixed it.

**Comment by raedwulf** [comment]
Okay reasonably confident I know what is going on now.
`clock_gettime(CLOCK_MONOTONIC, ...)` typically starts from boot time at 0.

In which case there is little need to detect wrap-arounds or other behaviour. The only remaining tasks relating to this issue are:

- Document 0 behaviour and assumptions about CLOCK_MONOTONIC.
- Perhaps use CLOCK_MONOTONIC_PRECISE on FreeBSD; it appears from the documentation that CLOCK_MONOTONIC uses CLOCK_MONOTONIC_FAST which seems to be the analogue to Linux's CLOCK_MONOTONIC_COARSE which is probably not our desired behaviour? Linux's CLOCK_MONOTONIC seems closer to FreeBSD's CLOCK_MONOTONIC_PRECISE.

[FreeBSD clock_gettime](https://www.freebsd.org/cgi/man.cgi?query=clock_gettime)
[Linux clock_gettime](http://man7.org/linux/man-pages/man2/clock_gettime.2.html)

**Comment by sustrik** [comment]
I would just go with CLOCK_MONOTONIC for now. It seems to be the most generic option.

**Comment by raedwulf** [comment]
I'll close this as I think it's pretty much resolved.  I'm not sure if there is any issue with CLOCK_MONOTONIC on FreeBSD either, so let's close this for now.
