### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by wirebirdlabs** [sustrik/libdill#6]
Is it within the scope and desire of this project to support modern Windows platforms?

**Comment by sustrik** [comment]
Meh. Too much work for too little benefit.

**Comment by wirebirdlabs** [comment]
Understood. Is that more from the perspective "I don't want/need to do it myself", or "It's against the spirit/trajectory at this time; a non-goal right now"?

**Comment by sustrik** [comment]
Non goal for me, personally. If you want to give it a try, start with porting libmill. That one's stable. libdill is a moving target.

**Comment by wirebirdlabs** [comment]
Thanks! Closing this inquiry.

**Comment by mewalig** [comment]
I'm posting an update that will get it to at least compile on Win. Have not tested that it actually works yet.
