### ISSUE TITLE
[Bug] Stack unwinding fails in assembly context switching

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libdill#64]
The stack unwinding in the assembly implementation is broken; stack traces lose information usually past the last `dill_wait` call.

**Comment by raedwulf** [comment]
@sustrik is there a test case I could debug?

**Comment by sustrik** [comment]
To reproduce:

1. Add dill_aseert(0) at cr.c:409
2. ./configure --disable-shared --enable-debug
2. make check
3. gdb ./tests/example
4. r
5. bt

**Comment by raedwulf** [comment]
Fixed it; cfi directives need to be at the end of a function body otherwise it conflicts with other unwinding information.  Will submit PR in a few minutes.
