### ISSUE TITLE
[Cleanup] Possible redundant condition

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libdill#70]
https://github.com/sustrik/libdill/blob/master/cr.c#L387
```C
    /* Store the context of the current coroutine, if any. */
    if(ctx->r) {
```
I think this condition is redundant - because `ctx->r` should always be set when it enters this function.

@sustrik can you double check if this is the case?

**Comment by sustrik** [comment]
I think this may be a leftover from earlier stages of development where a lot of stuff was initialized using ={0}. In any case, it looks obsolete. Let's get rid of it.
