### ISSUE TITLE
"coroutine" switch strange, does this work correctly 

### ISSUE THREAD

**Issue by winimi** [sustrik/libdill#80]
here is example code, 

example.c 

`#include <stdio.h>

#include "assert.h"
#include "../libdill.h"

int secs = 0;

coroutine void worker(const char *text) {
    while(1) {
        printf("[%3d]----------------%s-------------\n", ++secs, text);
        yield();
        sleep(1);
    }
}

int main() {
    int cr1 = go(worker("0 -- text"));
    errno_assert(cr1 >= 0);
    int cr2 = go(worker("1 -- text"));
    errno_assert(cr2 >= 0);
    int rc = msleep(now() + 100);
    errno_assert(rc == 0); 
    rc = hclose(cr1);
    errno_assert(rc == 0);
    rc = hclose(cr2);
    errno_assert(rc == 0);
    return 0;
}
`

I compile with   " gcc ./example.c  -o example -ldill "
centos 6.2 32bit

here is the log

`
[hash@centos tests]$ gcc ./example.c  -o example -ldill
[hash@centos tests]$ ./example
[  1]----------------0 -- text-------------

[  2]----------------1 -- text-------------
[  3]----------------0 -- text-------------
[  4]----------------1 -- text-------------
[  5]----------------0 -- text-------------
[  6]----------------1 -- text-------------
[  7]----------------0 -- text-------------
[  8]----------------1 -- text-------------
[  9]----------------0 -- text-------------
[ 10]----------------1 -- text-------------
[ 11]----------------0 -- text-------------
[ 12]----------------1 -- text-------------
[ 13]----------------0 -- text-------------
.
.
.
[105]----------------0 -- text-------------
[106]----------------1 -- text-------------
**_[107]----------------0 -- text-------------
[108]----------------0 -- text-------------
[109]----------------0 -- text-------------
[110]----------------0 -- text-------------
[111]----------------0 -- text-------------
[112]----------------0 -- text-------------
[113]----------------0 -- text-------------
[114]----------------0 -- text-------------
[115]----------------0 -- text-------------
[116]----------------0 -- text-------------
[117]----------------0 -- text-------------
[118]----------------0 -- text-------------
[119]----------------0 -- text-------------
[120]----------------0 -- text-------------
[121]----------------0 -- text-------------
[122]----------------0 -- text-------------
[123]----------------0 -- text-------------
[124]----------------0 -- text-------------
[125]----------------0 -- text-------------
[126]----------------0 -- text-------------
[127]----------------0 -- text-------------
[128]----------------0 -- text-------------
[129]----------------0 -- text-------------
[130]----------------0 -- text-------------
[131]----------------0 -- text-------------
[132]----------------0 -- text-------------
[133]----------------0 -- text-------------
[134]----------------0 -- text-------------_**
`

after 100 times switch, the "1-text" coroutine never show again.

**Comment by sustrik** [comment]
You are missing the following line in the coroutine:

```
        int rc = yield();
        if(rc < 0 && errno == ECANCELED) return;
```

What happens is that `hclose(cr1)` asks the first coroutine to finish. However, the coroutine ignores the signal and loops on forever. The main coroutine remains stuck in the hclose() call.

That being said, the example highlights some problems with how libdill behaves under the load (sleep(1) is basically emulating 100% CPU load). I am not 100% sure on what the correct semantics should be though.

**Comment by ubergarm** [comment]
A few thoughts from a new guy:

1. It seems that sleep() blocks the coroutine loop. I'd suggest not using sleep().
2. Your coroutine functions never exit as written. They should be able to exit on hclose().
3. If you add prints, you'll notice your main function isn't continuing to execute as one might expect.

I invite you to consider this example where the coroutine's use msleep and exit when `hclose()` is called on their handle.  Hope this helps.

```
#include <stdio.h>

#include "assert.h"
#include "../libdill.h"

int secs = 0;

coroutine void worker(const char *text) {
    while(1) {
        printf("[%3d]----------------%s-------------\n", ++secs, text);
        int rc = msleep(now()+1000);
        if (rc != 0) {
            break;
        }
    }
}

int main() {
    printf("Starting\n");
    int cr1 = go(worker("0 -- text"));
    assert(cr1 >= 0);
    printf("zero started\n");
    int cr2 = go(worker("1 -- text"));
    assert(cr2 >= 0);
    printf("one started\n");
    int rc = msleep(now() + 10000);
    printf("msleep over\n");
    assert(rc == 0);
    rc = hclose(cr1);
    printf("zero closed\n");
    assert(rc == 0);
    rc = hclose(cr2);
    printf("one closed\n");
    assert(rc == 0);
    printf("all done\n");
    return 0;
}
```

**Comment by sustrik** [comment]
Maybe documentation should be more explicit on how coroutines are shut down...

**Comment by winimi** [comment]
@sustrik @ubergarm thanks, that really helps. 👍

**Comment by sustrik** [comment]
To alleviate the problem, I've changed the algorithm to perform poll (checking timers and external events) at least once a second instead of once per 103 context switches which used to be the case.
