### ISSUE TITLE
libdill implementation of python >=3.5 asyncio event loop?

### ISSUE THREAD

**Issue by ubergarm** [sustrik/libdill#87]
Basically wondering if it might be possible or even make sense to repeat with `libdill` what the [MagicStack](https://magic.io/blog/uvloop-blazing-fast-python-networking/) folks did with [libuv](http://libuv.org/)?

All the features required by such an event loop may be [beyond the scope](http://250bpm.com/blog:50/comments/show#post-2314711) of `libdill` alone.

Anyway, for funzies I threw up a place holder repo over at [ubergarm/dillloop](https://github.com/ubergarm/dillloop). If nothing else, it may be amusing to get Python bindings for coroutines and channels.

Cheers!

**Comment by sustrik** [comment]
Nice. Btw, there was a similar thing done for Swift: https://github.com/Zewo/Venice
