### ISSUE TITLE
reading strips from tiff file

### ISSUE THREAD

**Issue by rkanavath** [sustrik/libdill#93]
I have this method[1] that can read individual strips from a tiff file.
[1] http://www.libtiff.org/man/TIFFReadEncodedStrip.3t.html

Is there a way to use libdill to read multiple strips at the same time?
Not sure having more cpu cores will help this to achieve concurrency

**Comment by sustrik** [comment]
libdill does concurrency, not parallelism. If you need parallelism you have to create threads/processes as usual.
