### ISSUE TITLE
Use without install libdill

### ISSUE THREAD

**Issue by siscia** [sustrik/libdill#95]
Hi all,

maybe the question is quite naive, however I wasn't able to come up with any solution.

In a project I am developing I am considering to use libdill, however I need it to don't be installed in the machine.
I need libdill inside a folder, then compile it and link it to my library, without installing it to my host machine.

Are there any way to achieve this?

Best,

**Comment by sustrik** [comment]
./configure --prefix <mypath>

**Comment by siscia** [comment]
:+1:
