### ISSUE TITLE
macports as problem with .cfi ops

### ISSUE THREAD

**Issue by rurban** [sustrik/libdill#96]
On darwin with macports `as` being installed (at `/opt/local/bin/as`) and the default gcc being the macports gcc, the assembler doesn't know about the .cfi ops.
```
  CC       libdill_la-cr.lo
  CC       libdill_la-now.lo
  CC       libdill_la-pollset.lo
  CC       libdill_la-rbtree.lo
cr.c:383:Unknown pseudo-op: .cfi_def_cfa
cr.c:383:Rest of line ignored. 1st junk character valued 37 (%).
cr.c:384:Unknown pseudo-op: .cfi_offset
cr.c:384:Rest of line ignored. 1st junk character valued 37 (%).
cr.c:385:Unknown pseudo-op: .cfi_offset
...
```

The fix is to use `CC=/usr/bin/cc ./configure` which bypasses the broken macports assembler.
This probably needs a configure probe.

**Comment by sustrik** [comment]
What should the probe check for?

**Comment by rurban** [comment]
For those assembler errors above.
I'll test it then.

**Comment by sustrik** [comment]
I am not sure what can be done here. It seems to be up to the user to provide a compiler that works.

We can check for a specific bad version of the compiler and print out a comprehensive error message but that's not going to be much better than what we have now.

We can't automatically redirect compiler to /usr/bin/cc as there's no guarantee that that one will work.

**Comment by rurban** [comment]
A broken compiler/assembler can be probed for. That's why we have a configure.ac

**Comment by sustrik** [comment]
Sure, we can probe for it. But the question is what would you replace it by? It's up to the user to decide what compiler they want to use.

**Comment by rurban** [comment]
The probe could abort with a useful error message, to hint how to specify a working compiler.

**Comment by sustrik** [comment]
Ok, that makes sense. Can you provide a minimal example of code that breaks with your compiler? Also, what's the compiler name & version?

**Comment by rurban** [comment]
I'll write a probe, but not this week. Ok?

**Comment by sustrik** [comment]
Great, thanks!

**Comment by sustrik** [comment]
@raedwulf: You may have an optinion on this as you've written the code in question.

**Comment by raedwulf** [comment]
You can remove the pseudo-ops although it is bizarre that they are not present. It's likely that the compiler is older? What version of os x, gcc and as are you using?

**Comment by rurban** [comment]
I should rather file a macports ticket. These assembler bugs drive me crazy everywhere also.
The recommended solution (something the probe could do) is to add `-Wa,-q` to use the integrated as and not an external outdated one.
https://stackoverflow.com/questions/9840207/how-to-use-avx-pclmulqdq-on-mac-os-x

**Comment by sustrik** [comment]
Ok, I am going to close this ticket. Please, reopen if needed.
